#!/bin/bash -v

sudo zypper --quiet install --no-recommends -y bash-completion
sudo zypper --quiet install --no-recommends -y boost-license1_46_1
sudo zypper --quiet install --no-recommends -y calibre
sudo zypper --quiet install --no-recommends -y check
sudo zypper --quiet install --no-recommends -y ConsoleKit-x11
sudo zypper --quiet install --no-recommends -y dbus-1-x11
sudo zypper --quiet install --no-recommends -y eject
sudo zypper --quiet install --no-recommends -y epdfview
sudo zypper --quiet install --no-recommends -y freeglut-devel
sudo zypper --quiet install --no-recommends -y gcc-c++
sudo zypper --quiet install --no-recommends -y gcc-fortran
sudo zypper --quiet install --no-recommends -y gnome-icon-theme
sudo zypper --quiet install --no-recommends -y gnome-packagekit
sudo zypper --quiet install --no-recommends -y graphviz
sudo zypper --quiet install --no-recommends -y graphviz-devel
sudo zypper --quiet install --no-recommends -y graphviz-gd
sudo zypper --quiet install --no-recommends -y grub
sudo zypper --quiet install --no-recommends -y gstreamer-utils
sudo zypper --quiet install --no-recommends -y gvim
sudo zypper --quiet install --no-recommends -y hunspell
sudo zypper --quiet install --no-recommends -y icedtea-web
sudo zypper --quiet install --no-recommends -y iputils
sudo zypper --quiet install --no-recommends -y java-1_6_0-openjdk-devel
sudo zypper --quiet install --no-recommends -y less
sudo zypper --quiet install --no-recommends -y libboost_date_time1_46_1
sudo zypper --quiet install --no-recommends -y libboost_filesystem1_46_1
sudo zypper --quiet install --no-recommends -y libboost_graph1_46_1
sudo zypper --quiet install --no-recommends -y libboost_iostreams1_46_1
sudo zypper --quiet install --no-recommends -y libboost_math1_46_1
sudo zypper --quiet install --no-recommends -y libboost_mpi1_46_1
sudo zypper --quiet install --no-recommends -y libboost_program_options1_46_1
sudo zypper --quiet install --no-recommends -y libboost_python1_46_1
sudo zypper --quiet install --no-recommends -y libboost_random1_46_1
sudo zypper --quiet install --no-recommends -y libboost_regex1_46_1
sudo zypper --quiet install --no-recommends -y libboost_serialization1_46_1
sudo zypper --quiet install --no-recommends -y libboost_signals1_46_1
sudo zypper --quiet install --no-recommends -y libboost_system1_46_1
sudo zypper --quiet install --no-recommends -y libboost_test1_46_1
sudo zypper --quiet install --no-recommends -y libboost_thread1_46_1
sudo zypper --quiet install --no-recommends -y libboost_wave1_46_1
sudo zypper --quiet install --no-recommends -y libcurl-devel
sudo zypper --quiet install --no-recommends -y libgnome
sudo zypper --quiet install --no-recommends -y libgnomesu
sudo zypper --quiet install --no-recommends -y libpcre0
sudo zypper --quiet install --no-recommends -y libpcrecpp0
sudo zypper --quiet install --no-recommends -y libpcreposix0
sudo zypper --quiet install --no-recommends -y libpng14-devel
sudo zypper --quiet install --no-recommends -y libqt4-sql-sqlite
sudo zypper --quiet install --no-recommends -y libQtGStreamer-0_10-0
sudo zypper --quiet install --no-recommends -y libQtWebKit4
sudo zypper --quiet install --no-recommends -y libxerces-c-3_0
sudo zypper --quiet install --no-recommends -y libxml2-devel
sudo zypper --quiet install --no-recommends -y lightdm
sudo zypper --quiet install --no-recommends -y lxappearance
sudo zypper --quiet install --no-recommends -y lxappearance-obconf
sudo zypper --quiet install --no-recommends -y lxcc
sudo zypper --quiet install --no-recommends -y lxde-common
sudo zypper --quiet install --no-recommends -y lxinput
sudo zypper --quiet install --no-recommends -y lxlauncher
sudo zypper --quiet install --no-recommends -y lxmenu-data
sudo zypper --quiet install --no-recommends -y lxpanel
sudo zypper --quiet install --no-recommends -y lxrandr
sudo zypper --quiet install --no-recommends -y lxsession
sudo zypper --quiet install --no-recommends -y lxsession-edit
sudo zypper --quiet install --no-recommends -y lxshortcut
sudo zypper --quiet install --no-recommends -y lxtask
sudo zypper --quiet install --no-recommends -y lxterminal
sudo zypper --quiet install --no-recommends -y make
sudo zypper --quiet install --no-recommends -y man
sudo zypper --quiet install --no-recommends -y menu-cache
sudo zypper --quiet install --no-recommends -y MozillaFirefox
sudo zypper --quiet install --no-recommends -y NetworkManager
sudo zypper --quiet install --no-recommends -y ntp
sudo zypper --quiet install --no-recommends -y nuoveXT2-icon-theme
sudo zypper --quiet install --no-recommends -y obconf
sudo zypper --quiet install --no-recommends -y obmenu
sudo zypper --quiet install --no-recommends -y openbox
sudo zypper --quiet install --no-recommends -y PackageKit
sudo zypper --quiet install --no-recommends -y parcellite
sudo zypper --quiet install --no-recommends -y pcmanfm
sudo zypper --quiet install --no-recommends -y pdfminer
sudo zypper --quiet install --no-recommends -y perl-Browser-Open
sudo zypper --quiet install --no-recommends -y perl-DBD-Pg
sudo zypper --quiet install --no-recommends -y perl-DBD-SQLite
sudo zypper --quiet install --no-recommends -y perl-JSON
sudo zypper --quiet install --no-recommends -y perl-JSON-Any
sudo zypper --quiet install --no-recommends -y perl-JSON-DWIW
sudo zypper --quiet install --no-recommends -y perl-JSON-Parse
sudo zypper --quiet install --no-recommends -y perl-JSON-PP
sudo zypper --quiet install --no-recommends -y perl-JSON-RPC
sudo zypper --quiet install --no-recommends -y perl-JSON-XS
sudo zypper --quiet install --no-recommends -y perl-Net-Twitter
sudo zypper --quiet install --no-recommends -y perl-WWW-Mechanize
sudo zypper --quiet install --no-recommends -y perl-YAML
sudo zypper --quiet install --no-recommends -y perl-YAML-LibYAML
sudo zypper --quiet install --no-recommends -y perl-YAML-Perl
sudo zypper --quiet install --no-recommends -y perl-YAML-Syck
sudo zypper --quiet install --no-recommends -y perl-YAML-Tiny
sudo zypper --quiet install --no-recommends -y pgadmin3
sudo zypper --quiet install --no-recommends -y pk-update-icon
sudo zypper --quiet install --no-recommends -y postgresql
sudo zypper --quiet install --no-recommends -y postgresql-contrib
sudo zypper --quiet install --no-recommends -y postgresql-devel
sudo zypper --quiet install --no-recommends -y pstoedit
sudo zypper --quiet install --no-recommends -y python-django
sudo zypper --quiet install --no-recommends -y R-base
sudo zypper --quiet install --no-recommends -y R-base-devel
sudo zypper --quiet install --no-recommends -y ruby
sudo zypper --quiet install --no-recommends -y sqlite3-devel
sudo zypper --quiet install --no-recommends -y sudo
sudo zypper --quiet install --no-recommends -y SuSEfirewall2
sudo zypper --quiet install --no-recommends -y syslog-ng
sudo zypper --quiet install --no-recommends -y tesseract
sudo zypper --quiet install --no-recommends -y tk-devel
sudo zypper --quiet install --no-recommends -y vim
sudo zypper --quiet install --no-recommends -y vim-data
sudo zypper --quiet install --no-recommends -y vim-enhanced
sudo zypper --quiet install --no-recommends -y wget
sudo zypper --quiet install --no-recommends -y x11-tools
sudo zypper --quiet install --no-recommends -y xarchiver
sudo zypper --quiet install --no-recommends -y xfce4-screenshooter
sudo zypper --quiet install --no-recommends -y xorg-x11-driver-input
sudo zypper --quiet install --no-recommends -y xorg-x11-driver-video
sudo zypper --quiet install --no-recommends -y xorg-x11-fonts
sudo zypper --quiet install --no-recommends -y xorg-x11-server
sudo zypper --quiet install --no-recommends -y xpdf-poppler
sudo zypper --quiet install --no-recommends -y yast2
sudo zypper --quiet install --no-recommends -y yast2-control-center
sudo zypper --quiet install --no-recommends -y yast2-firewall
sudo zypper --quiet install --no-recommends -y yast2-firstboot
sudo zypper --quiet install --no-recommends -y yast2-ncurses
sudo zypper --quiet install --no-recommends -y yast2-ntp-client
sudo zypper --quiet install --no-recommends -y yast2-runlevel
sudo zypper --quiet install --no-recommends -y yast2-sudo
sudo zypper --quiet install --no-recommends -y zypper
