#!/bin/bash -v

sudo zypper install -y bash-completion
sudo zypper install -y epdfview
sudo zypper install -y freeglut-devel
sudo zypper install -y gcc-c++
sudo zypper install -y gcc-fortran
sudo zypper install -y graphviz
sudo zypper install -y graphviz-devel
sudo zypper install -y graphviz-gd
sudo zypper install -y gvim
sudo zypper install -y icedtea-web
sudo zypper install -y java-1_6_0-openjdk-devel
sudo zypper install -y juffed
sudo zypper install -y juffed-plugins
sudo zypper install -y libcurl-devel
sudo zypper install -y libpng14-devel
sudo zypper install -y libQtWebKit4
sudo zypper install -y libxml2-devel
sudo zypper install -y lightdm
sudo zypper install -y make
sudo zypper install -y MozillaFirefox
sudo zypper install -y NetworkManager
sudo zypper install -y ntp
sudo zypper install -y obconf
sudo zypper install -y openbox
sudo zypper install -y open-vm-tools
sudo zypper install -y open-vm-tools-gui
sudo zypper install -y oxygen-icon-theme
sudo zypper install -y perl-Browser-Open
sudo zypper install -y perl-JSON
sudo zypper install -y perl-JSON-XS
sudo zypper install -y perl-Net-Twitter
sudo zypper install -y perl-WWW-Mechanize
sudo zypper install -y perl-YAML
sudo zypper install -y perl-YAML-Syck
sudo zypper install -y python-gtk
sudo zypper install -y python-xml
sudo zypper install -y qlipper
sudo zypper install -y qstardict
sudo zypper install -y qterminal
sudo zypper install -y qxkb
sudo zypper install -y razorqt
sudo zypper install -y R-patched
sudo zypper install -y R-patched-devel
sudo zypper install -y rssguard
sudo zypper install -y ruby
sudo zypper install -y sudo
sudo zypper install -y tesseract
sudo zypper install -y texinfo
sudo zypper install -y texlive-bin
sudo zypper install -y texlive-bin-latex
sudo zypper install -y tk-devel
sudo zypper install -y vim-base
sudo zypper install -y vim-data
sudo zypper install -y vim-enhanced
sudo zypper install -y virtualbox-guest-tools
sudo zypper install -y virtualbox-guest-x11
sudo zypper install -y wget
sudo zypper install -y xscreensaver
sudo zypper install -y yast2-firewall
sudo zypper install -y yast2-ntp-client
sudo zypper install -y yast2-sudo
